name: adhan
description: Adhan for Dart / Muslim Prayer Times Library. Now retrieving Prayer time in Dart easier than ever.
version: 1.1.16
homepage: https://github.com/iamriajul/adhan-dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  intl: ^0.18.0
  dart_numerics: ^0.0.5
  test_coverage: ^0.5.0
  enum_to_string: ^2.0.1
  strings: ^0.2.2
  path: ^1.7.0
  timezone: ^0.9.0
